name: Pull Request
description: Template for submitting pull requests
title: "PR: [Your Title Here]"
labels: [pull request]
body:
  - type: markdown
    attributes:
      value: |
        # Description
        Please include a summary of the change, the issue it addresses, and any dependencies.

        Fixes # (issue number)

  - type: checkboxes
    attributes:
      label: Type of Change
      options:
        - label: Bug fix (non-breaking change which fixes an issue)
        - label: New feature (non-breaking change which adds functionality)
        - label: Breaking change (fix or feature that would cause existing functionality not to work as expected)
        - label: Documentation update

  - type: markdown
    attributes:
      value: |
        ## Testing
        Describe the tests that you ran to verify your changes.

  - type: checkboxes
    attributes:
      label: Checklist
      options:
        - label: I have performed a self-review of my own code
        - label: I have commented my code, particularly in hard-to-understand areas
        - label: I have made corresponding changes to the documentation
        - label: My changes generate no new warnings
        - label: I have added tests that prove my fix is effective or that my feature works
        - label: New and existing unit tests pass locally with my changes
        - label: Any dependent changes have been merged and published in downstream modules

  - type: markdown
    attributes:
      value: |
        ## Screenshots
        Attach any screenshots or visual representations of the changes (if applicable).
